#!/bin/sh

Directory="$(find . -type f | grep -v "^./.git" |
    git check-ignore --verbose --non-matching --stdin |
    sed -n -e 's,\t./,\t,' -e 's,^::\t*,,p')"

	for FileName in $Directory
	do
	EOLCHAR="$(tail -c 1 $FileName)"
	EndChar=";"
		if [[ $EOLCHAR != $EndChar ]]; then
			echo "End of line not end with ; in $FileName"
		fi	
	done
  
