#!/bin/sh

Directory="$(find . -type f | grep -v "^./.git" |
    git check-ignore --verbose --non-matching --stdin |
    sed -n -e 's,\t./,\t,' -e 's,^::\t*,,p')"
CNT=0
	for FileName in $Directory
	do
	ERRSTRING='Error'
	if echo $FileName | grep -iqF $ERRSTRING; then
		echo "Error word found in $FileName"
		let CNT++
	fi
	done
	if ((CNT > 0)); then
		echo "Aborting commit due to Error word present"
		exit 1
	fi	
	exit 0